TRS.UI/Models/TaskReport.cs
using System;

namespace TRS.DataAccess.Models
{
    public class TaskReport
    {
        public Guid Id { set; get; }
        public DateTime DateOfReport { set; get; }
        public DateTime DateEdit { set; get; }
        public int Effort { set; get; }
        public string Description { set; get; }
        public Guid TaskId { set; get; }
        public Guid UserId { set; get; }
    }
}

TRS.UI/Models/TaskReportViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TRS.UI.Models
{
    public class TaskReportViewModel
    {
        public Guid Id { set; get; }
        [Required]
        public DateTime DateOfReport { set; get; }
        [Required]
        public DateTime DateEdit { set; get; }
        [Required]
        public int Effort { set; get; }
        [Required]
        public string Description { set; get; }
        public Guid Task_Id { set; get; } //i don't know pochemu s TaskId ne rabotaet
        public Guid UserId { set; get; }
    }
}

TRS.UI/Controllers/TaskReportController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading;
using System.Web.Mvc;
using TRS.UI.Models;


namespace TRS.UI.Controllers
{
    public class TaskReportController : Controller
    {
        private readonly ServiceReferenceTaskReport.ITaskReportService _taskReportService;
        // GET: TaskReport
        public TaskReportController(/*ITaskReportService taskReportService*/)
        {
            _taskReportService = new ServiceReferenceTaskReport.TaskReportServiceClient();
        }
        public ActionResult CreateTaskReport(Guid token)
        {
            var currentUser = Thread.CurrentPrincipal.Identity as ClaimsIdentity;
            var taskReport = _taskReportService.ShowTaskReportDetails(token);
            taskReport.UserId = Guid.Parse(currentUser.GetUserId());
            var _taskReport = Mapper.Map<TaskReportViewModel>(taskReport);
            return View(_taskReport);
        }

        public ActionResult ShowTaskReport(Guid token, string project)
        {
            ServiceReferenceTaskReport.TaskReport[] tasksReport;
            var currentUser  = Thread.CurrentPrincipal.Identity as ClaimsIdentity;
            if (currentUser.HasClaim("Manager", project) 
                || currentUser.HasClaim(ClaimTypes.Role, "admin"))
                tasksReport = _taskReportService.ShowAllTaskReport(token);
            else if (currentUser.HasClaim("User", token.ToString()))
                tasksReport = _taskReportService.ShowTaskReport(token, Guid.Parse(currentUser.GetUserId()));

            else throw new NotImplementedException("ACCESS DENIED");
            var view = Mapper.Map<IEnumerable<TaskReportViewModel>>(tasksReport);
            return View(view);
        }
        [HttpPost]
        public ActionResult CreateTaskReport(TaskReportViewModel taskReport)
        {
            if (!ModelState.IsValid)
            {
                return View(taskReport);
            }
            taskReport.DateEdit=DateTime.Now;
            var domainTaskReport = Mapper.Map<ServiceReferenceTaskReport.TaskReport>(taskReport);
            _taskReportService.AddTaskReport(domainTaskReport);
            return RedirectToAction("Index","Home");
        }
    }
}

TRS.UI/Views/TaskReport/CreateTaskReport.cshtml
@using TRS.UI.Infrastructure
@model TRS.UI.Models.TaskReportViewModel

@{
}
<div class="panel panel-default">
    <div class="panel-heading">
        @Resources.Resource.Field_CreateTaskReport
    </div>
    <div class="panel-body">
        <div class="container-fluid">@Html.ValidationSummary()</div>
        @using (Html.BeginForm("CreateTaskReport", "TaskReport", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.HiddenFor(taskReport => taskReport.Id)
            @Html.HiddenFor(taskReport => taskReport.UserId)
            @Html.HiddenFor(t => t.Task_Id)
            @Html.HiddenFor(taskReport => taskReport.DateEdit)
            <div class="form-group">
                @Html.Label(@Resources.Resource.Field_Description, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextBoxFor(taskReport => taskReport.Description, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(taskReport => taskReport.Description)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.Label(@Resources.Resource.Field_Effort, new { @class = "col-xs-2 control-label" })
                <div class="col-xs-10">
                    @Html.TextBoxFor(taskReport => taskReport.Effort, new { @class = "form-control" })
                    <div>
                        @Html.ValidationMessageFor(taskReport => taskReport.Effort)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.Label(@Resources.Resource.Field_DateOfReport, new {@class = "col-xs-2 control-label"})

                <div class="col-xs-10">
                    @Html.DatepickerFor(taskReport => taskReport.DateOfReport, new {@class = "form-control"})
                    <div>
                        @Html.ValidationMessageFor(taskReport => taskReport.DateOfReport)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="submit" class="btn btn-primary">@Resources.Resource.Button_Save</button>
                </div>
            </div>
        }
    </div>
</div>

TRS.UI/Views/TaskReport/ShowTaskReport.cshtml
@using System.Security.Claims

@model IEnumerable<TRS.UI.Models.TaskReportViewModel>
@{
    ViewBag.Title = "Task Report";
    var claimsIdentity = User.Identity as ClaimsIdentity;
}
<h4>@Resources.Resource.Title_TaskReport</h4>
<table class="table table-responsive table-hover table-condensed">
    <thead>
        <tr>
            <th>@Resources.Resource.Field_Description</th>
            <th>@Resources.Resource.Field_Effort</th>
            <th>@Resources.Resource.Field_StartDate</th>
            <th>@Resources.Resource.Field_EndDate</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() != 0)
        {
            foreach (var taskReport in Model)
            {
                if (User != null && User.Identity.IsAuthenticated)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(c => taskReport.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(c => taskReport.Effort)
                        </td>
                        <td>
                            @Html.DisplayFor(c => taskReport.DateOfReport)
                        </td>
                        <td>
                            @Html.DisplayFor(c => taskReport.DateEdit)
                        </td>
                        <td>
                            @Html.ActionLink(@Resources.Resource.Button_EditTaskReport, "CreateTaskReport", "TaskReport", new { token = taskReport.Id }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>