TRS.UI/Models/Project.cs
using System;

namespace TRS.UI.Models
{
    public class Project
    {
        public Guid Id { set; get; }
        public string Name { set; get; }
        public string Description { set; get; }
        public DateTime StartDate { set; get; }
        public DateTime EndDate { set; get; }
    }
}

TRS.UI/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRS.UI.Models
{
    public class ProjectViewModel
    {
        public Guid Id { set; get; }
        [Required]
        public string Name { set; get; }
        [Required]
        public string Description { set; get; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { set; get; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { set; get; }
        [Required]
        public IEnumerable<string> Managers { set; get; } 
    }
}

TRS.UI/Controllers/AdminController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using TRS.UI.Infrastructure;
using TRS.UI.Models;
using TRS.UI.ServiceReferenceUser;


namespace TRS.UI.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        private readonly ServiceReferenceUser.IUserInfoService _userService;
        private readonly ServiceReferenceProject.IProjectService _projectService;
        private readonly ServiceReferenceUserRole.IUserRoleService _userRoleService;

        public AdminController(/*IUserService carService*/)
        {
            _userService = new UserInfoServiceClient();
            _projectService = new ServiceReferenceProject.ProjectServiceClient();
            _userRoleService = new ServiceReferenceUserRole.UserRoleServiceClient();
        }
        public ActionResult CreateProject(string token)
        {
            ViewBag.List = UsersHelper.GetAvaliableLocalizations(_userService);
            var project = token!= null ? _projectService.ShowProjectDetails(Guid.Parse(token)) : new ServiceReferenceProject.Project();
            if (token != null)
                MvcApplication.Log.Info("Edit Project "+token);
            else
                MvcApplication.Log.Info("Create New Project");
            return View(Mapper.Map<ProjectViewModel>(project));
        }
        [HttpPost]
        public ActionResult CreateProject(ProjectViewModel project)
        {
            if (project.Managers == null
                || (project.StartDate > project.EndDate)
                || _projectService.ShowProjectName(project.Name))
            {
                ViewBag.List = UsersHelper.GetAvaliableLocalizations(_userService);
                MvcApplication.Log.Info("Invalid data in Create Project View");
                return View(project);
            }
            var domainTask = Mapper.Map<ServiceReferenceProject.Project>(project);
            _projectService.EditProject(domainTask);
            _userRoleService.UpdateRoles(project.Id, project.Managers.ToArray(),1);
            MvcApplication.Log.Info("Create Project successful");
            return RedirectToAction("Index", "Home");
        }
    }
}

TRS.UI/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TRS.UI.Models;
using AutoMapper;

namespace TRS.UI.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        private readonly ServiceReferenceProject.IProjectService _projectService;
        public ProjectController(/*ServiceReferenceProject.IProjectService projectService*/)
        {
            _projectService = new ServiceReferenceProject.ProjectServiceClient();
        }
        public ActionResult Index()
        {
            var projectList = _projectService.ShowProject();
            var viewModel = Mapper.Map<IEnumerable<ProjectViewModel>>(projectList);
            MvcApplication.Log.Info("View projects");
            return View(viewModel);
        }
    }
}

TRS.UI/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TRS.UI.Models;
using AutoMapper;
using System.Security.Claims;
using System.Threading;
using Microsoft.AspNet.Identity;
using TRS.UI.Infrastructure;
using TRS.UI.ServiceReferenceTask;
using TRS.UI.ServiceReferenceUser;
using TRS.UI.ServiceReferenceUserRole;


namespace TRS.UI.Controllers
{
    public class TaskController : Controller
    {
        // GET: Project
        private readonly ServiceReferenceTask.ITaskService _taskService;
        private readonly ServiceReferenceUserRole.IUserRoleService _userRoleService;
        private readonly ServiceReferenceUser.IUserInfoService _userService;
        public TaskController()
        {
            _taskService = new TaskServiceClient();
            _userRoleService = new UserRoleServiceClient();
            _userService = new UserInfoServiceClient();
        }
        public ActionResult AllTasks(Guid token)
        {
            ServiceReferenceTask.Task[] tasks = null;
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity == null) return View(Mapper.Map<IEnumerable<TaskViewModel>>(tasks));
            if (claimsIdentity.HasClaim("Manager", token.ToString()) 
                || claimsIdentity.HasClaim(ClaimTypes.Role,"admin"))
                tasks = _taskService.ShowTasks(token);
            else if (claimsIdentity.HasClaim("User", token.ToString()))
            {
                var dd = _taskService.ShowTasks(token);
                var ff = Mapper.Map<IEnumerable<UI.Models.Task>>(dd);
                tasks = Mapper.Map<ServiceReferenceTask.Task[]>(ff.Where(tsk => (claimsIdentity.HasClaim("User", tsk.Id.ToString()) == true)));

                //_taskService.ShowTasks(token)
                //        .Where(tsk => (claimsIdentity.HasClaim("User", tsk.Id.ToString()) == true));
            }
            else throw new Exception("ACCESS DENIED");
            var viewModel = Mapper.Map<IEnumerable<TaskViewModel>>(tasks);
            ViewBag.Project = token;
            return View(viewModel);
        }
        public ActionResult CreateTask(string token)
        {
            ViewBag.List =  UsersHelper.GetAvaliableLocalizations(_userService);
            var currentUser = Thread.CurrentPrincipal.Identity as ClaimsIdentity;
            var task = _taskService.ShowTaskDetails(Guid.Parse(token));
            var dd = Mapper.Map<UI.Models.Task>(task);
            dd.Creator = Guid.Parse(currentUser.GetUserId());
            return View(Mapper.Map<TaskViewModel>(dd));
        }
        [HttpPost]
        public ActionResult CreateTask(TaskViewModel task)
        {
            if (task.Managers == null
                || (task.StartDate > task.EndDate)
                || _taskService.ShowTaskName(task.Name))
            {
                ViewBag.List = UsersHelper.GetAvaliableLocalizations(_userService);
                return View(task);
            }
            var domainTask = Mapper.Map<ServiceReferenceTask.Task>(task);
            _taskService.EditTask(domainTask);
            _userRoleService.UpdateRoles(task.Id, task.Managers.ToArray(), 2);
            _userRoleService.UpdateRoles(task.ProjectId, task.Managers.ToArray(), 2);
            return RedirectToAction("Index", "Home");
        }
    }
}

TRS.UI/Views/Project/Index.cshtml
@using System.Security.Claims
@model IEnumerable<TRS.UI.Models.ProjectViewModel>
@{
    ViewBag.Title = "Projects";
    var claimsIdentity = User.Identity as ClaimsIdentity;
    var labelBtn = "";
    var convertTimeZone = TimeZoneInfo.Utc;
    if (Request.Cookies.Get("Time") != null)
    {
        HttpCookie httpCookie = Request.Cookies.Get("Time");
        if (httpCookie != null)
        {
            convertTimeZone = TimeZoneInfo.FindSystemTimeZoneById(httpCookie.Value.ToString());
        }
    }
    DateTime k;
}

<h4>@Resources.Resource.Title_Project</h4>
@if (claimsIdentity.HasClaim(ClaimTypes.Role, "admin"))
{
    <div class="pull-right">@Html.ActionLink(@Resources.Resource.Button_CreateProject, "CreateProject", "Admin", new { projectId = ViewBag.Project }, new { @class = "btn btn-default btn-sm" })</div>
}
<table class="table table-responsive table-hover table-condensed">
    <thead>
        <tr>
            <th>@Resources.Resource.Field_NameProject</th>
            <th>@Resources.Resource.Field_Description</th>
            <th>@Resources.Resource.Field_StartDate</th>
            <th>@Resources.Resource.Field_EndDate</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var project in Model)
        {
            if (User != null && User.Identity.IsAuthenticated 
                && (claimsIdentity.HasClaim("Manager", project.Id.ToString()) 
                || claimsIdentity.HasClaim("User", project.Id.ToString())) 
                || (claimsIdentity.HasClaim(ClaimTypes.Role,"admin")))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(c => project.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(c => project.Description)
                    </td>
                    <td>
                        @{
                            project.StartDate = new DateTime(project.StartDate.Ticks, DateTimeKind.Unspecified);
                            k = TimeZoneInfo.ConvertTimeFromUtc(project.StartDate, convertTimeZone);
                        }
                        @k.ToShortDateString()
                    </td>
                    <td>
                        @{
                            project.EndDate = new DateTime(project.EndDate.Ticks, DateTimeKind.Unspecified);
                            k = TimeZoneInfo.ConvertTimeFromUtc(project.EndDate, convertTimeZone);
                        }
                        @k.ToShortDateString()
                    </td>

                        @if (claimsIdentity.HasClaim("Manager", project.Id.ToString())
                            || claimsIdentity.HasClaim(ClaimTypes.Role,"admin"))

                         {
                             labelBtn = @Resources.Resource.Button_ShowAllTasks;
                         }
                         else if (claimsIdentity.HasClaim("User", project.Id.ToString()))
                         {
                             labelBtn = @Resources.Resource.Button_ShowAvailableTask;
                         }
                    <td>
                        @Html.ActionLink(@labelBtn, "AllTasks", "Task", new {token = project.Id}, new {@class = "btn btn-default btn-sm"})
                    </td>
                    @if (claimsIdentity.HasClaim(ClaimTypes.Role, "admin"))
                    {
                        <td>
                            @Html.ActionLink(@Resources.Resource.Button_EditProject, "CreateProject", "Admin", new { token = project.Id }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    }

                </tr>
            }
        }
    </tbody>
</table>